# data source collection
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/link?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=America/New_York
    username: root
    password: 111813

rules:
  - !SHARDING
    tables:
      t_user:
        # Actual data nodes, e.g., database sources and actual tables in the database
        actualDataNodes: ds_0.t_user_${0..15}
        # Table sharding strategy
        tableStrategy:
          # Standard sharding scenario for a single sharding key
          standard:
            # Sharding key
            shardingColumn: username
            # Sharding algorithm，corresponding to rules[0].shardingAlgorithms
            shardingAlgorithmName: user_table_hash_mod
    # rules[0].shardingAlgorithms
    shardingAlgorithms:
      # Table sharding algorithm
      user_table_hash_mod:
        # Hash sharding based on the sharding key: username
        type: HASH_MOD
        # Number of shards
        props:
          sharding-count: 16
  - !ENCRYPT
    # Collection of encrypted table
    tables:
      # User table
      t_user:
        # Fields that need to be encrypted
        columns:
          # Phone number field，logical field correspond with field name in DO
          phone:
            # Cipher filed for phone number，this have to correspond with real column name in database
            cipherColumn: phone
            # Encryption algorithm
            encryptorName: common_encryptor
          email:
            cipherColumn: email
            encryptorName: common_encryptor
        # Query using ciphertext fields
        queryWithCipherColumn: true
    # Encryption algorithm
    encryptors:
      # Custom encryption algorithm name
      common_encryptor:
        # Encryption algorithm type
        type: AES
        props:
          # AES encryption key
          aes-key-value: d6oadClrrb9A3GWo

# Show logic SQL && actual SQL or not
props:
  sql-show: true